# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Epitceh Base
tagline:          'Epitech Libs, Tools & Templates'
description:      'Centralized repository of reusable C libraries, build tools, and project templates designed for EPITECH development workflows.'
url:              https://jarjarbin06.github.io/Epitech_Base
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/Jarjarbin06/Epitech_Base
