name: Build testing

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install CSFML
        run: |
          sudo apt-get update
          sudo apt-get install -y libcsfml-dev

      - name: Set compiler
        run: echo "CC=${{ matrix.compiler }}" >> $GITHUB_ENV

      - name: Build all libraries
        run: |
          set -e

          LIB_DIR="build_files/lib"

          for lib in "$LIB_DIR"/*; do
            if [ -d "$lib" ] && [ -f "$lib/Makefile" ]; then
              echo "===================================="
              echo "Building library: $(basename "$lib")"
              echo "===================================="

              make -C "$lib" fclean
              make -C "$lib" re
            else
              echo "Skipping $(basename "$lib") (no Makefile)"
            fi
          done
